<h1>
	Discharge Patient
	<small><?php echo $this->user->account_type_print; ?> Control Panel</small>
</h1>
                <!-- start:breadcrumb -->
                <ol class="breadcrumb">
                    <li><a href="<?php echo $this->baseUrl("/portal"); ?>"><i class="fa fa-home"></i> Dashboard</a></li>
                    <li><a href="#"> Forms</a></li>
                    <li class="active">Discharge Patient</li>
                </ol>
                <!-- end:breadcrumb -->

						<div class="row">
                            <div class="col-lg-12">
                            <form id="discharge" class="form-horizontal">
                            
                                <section class="panel">
                                    <header class="panel-heading">
                                        <h3>Medications</h3>
                                    </header>
                                    <div class="panel-body">
                                    	
                                    		<div class="form-group">
		                                        <label class="col-lg-3 col-sm-3 control-label"> </label>
		                                        <div class="col-lg-6 medlist">
		                                            <!-- Dynamic content added here -->
		                                        </div>
		                                    </div>
                                    	
                                            <div class="form-group">
		                                        <label class="col-lg-3 col-sm-3 control-label">Add Medications</label>
		                                        <div class="col-lg-4">
		                                            <div class="iconic-input">
		                                                <i class="fa fa-search"></i>
		                                                <input type="text" id="meds" class="form-control" placeholder="Buspiorne">
		                                            </div>
		                                        </div>
		                                    </div>
                                        
                                    </div>
                                </section>
                                
                                <section class="panel">
                                    <header class="panel-heading">
                                        <h3>Max Allowed Activity Level</h3>
                                    </header>
                                    <div class="panel-body">
                                   			<div class="form-group">
		                                        <label class="col-lg-3 col-sm-3 control-label"> </label>
		                                        <div class="col-lg-6">
		                                            <div class="radio">
		                                                <label>
		                                                    <input type="radio" name="optionsRadios" id="optionsRadios1" value="3" checked="">
		                                                    High Activity Allowed - 30 minutes or more of elevated heart rate/day.
		                                                </label>
		                                            </div>
		                                            <div class="radio">
		                                                <label>
		                                                    <input type="radio" name="optionsRadios" id="optionsRadios1" value="2" checked="">
		                                                    Moderate Excersice Recommended - 15 to 30 minutes of elevated heart rate/day.
		                                                </label>
		                                            </div>
		                                            <div class="radio">
		                                                <label>
		                                                    <input type="radio" name="optionsRadios" id="optionsRadios1" value="1" checked="">
		                                                    Mild Excersice Recommended - 5 to 15 minutes of elevated heart rate/day.
		                                                </label>
		                                            </div>
		                                        </div>
		                                    </div>
                                    </div>
                                </section>
                                
                                <section class="panel">
                            
                                    <div class="panel-body">
                                    	<button style="margin-left:calc(50%)" type="submit" class="btn btn-info" data-original-title="" title="">Submit</button>
                                    </div>
                                    
                                </section>
                            </div>
                            </form>
                        </div>
                        
                        
                        
<script>
	

	$('#meds').bind('keypress', function(e) {
		if(e.keyCode==13){
			event.preventDefault();
			var medication = $('#meds').val();
			$( ".medlist" ).append( $( 
					'<div class="input-group row entry_'+count+'">'+
					'<input class="form-control" style="width:300px" type="text" placeholder="'+medication+'" disabled="'+medication+'">'+
					'<input type="hidden" name="medication_'+count+'" value="'+medication+'">'+
					'<select class="input-group form-control m-bot15" name="times_'+count+'" style="display:inline; width:220px">'+
                    	'<option>Once/Day</option>'+
                    	'<option>Twice/Day</option>'+
                    	'<option>Three times/Day</option>'+
                    	'<option>Four times/Day</option>'+
                    	'<option>Five times/Day</option>'+
                	'</select>'+
					'<span class="input-group-btn">'+
                    '<button class="btn btn-danger" id="del_'+count+'" type="button" data-original-title="" title="">X</button>'+
                	'</span></div>'
			 ) );
			$('#meds').val('');
			// The remove button click
		    $("#del_"+count).click(function() {
		        var buttonId = $(this).attr("id");
		        //write the logic for removing from the array
		        $("#entry_"+count).remove();            
		    });
			count++;
		}
	});
	$('#discharge').on('submit', function(e) {
	    //prevent the default submithandling
	    e.preventDefault();
	    //send the data of 'this' (the matched form) to yourURL
	    $.post('<?php echo $this->baseUrl("portal/discharge"); ?>', $(this).serialize());
	});


  $(function() {
    var availableTags = [
      "Abarelix",
      "Ablavar",
      "Acarbose",
      "Acetaminophen",
      "Acticin",
      "Actiq",
      "Activase",
      "Acular",
      "Adapalene",
      "Adderall"
    ];
    $( "#meds" ).autocomplete({
      source: availableTags
    });
  });

  var count = 0;
</script>