<h1>
	Discharge Data Saved
	<small><?php echo $this->user->account_type_print; ?> Control Panel</small>
</h1>
                <!-- start:breadcrumb -->
                <ol class="breadcrumb">
                    <li><a href="<?php echo $this->baseUrl("/portal"); ?>"><i class="fa fa-home"></i> Dashboard</a></li>
                    <li><a href="#"> Forms</a></li>
                    <li class="active">Discharge Patient</li>
                </ol>
                <!-- end:breadcrumb -->

						<div class="row">
                            <div class="col-lg-12">
                                <section class="panel">
                                    <header class="panel-heading">
                                        <h3>Data has been sent to the paitent's wearable!</h3>
                                    </header>
                                    <img src="<?php echo $this->baseUrl("/"); ?>img/wearables.jpg" />
                                </section>
                                
                              
                            </div>
                        </div>
                        
