<h1>
	Discharge Patient
	<small><?php echo $this->user->account_type_print; ?> Control Panel</small>
</h1>
                <!-- start:breadcrumb -->
                <ol class="breadcrumb">
                    <li><a href="<?php echo $this->baseUrl("/portal"); ?>"><i class="fa fa-home"></i> Dashboard</a></li>
                    <li><a href="#"> Forms</a></li>
                    <li class="active">Discharge Patient</li>
                </ol>
                <!-- end:breadcrumb -->

<div class="row">
                            <div class="col-lg-12">
                                <section class="panel">
                                    <header class="panel-heading">
                                        Medications
                                    </header>
                                    <div class="panel-body">
                                        <form action="#" class="form-horizontal">
                                            
                                            
                                            <div class="form-group">
		                                        <label class="col-lg-3 col-sm-3 control-label">Add Medications</label>
		                                        <div class="col-lg-4">
		                                            <div class="iconic-input">
		                                                <i class="fa fa-search"></i>
		                                                <input type="text" id="#meds" class="form-control" placeholder="Buspiorne">
		                                            </div>
		                                        </div>
		                                    </div>
                                           
                                        </form>
                                    </div>
                                </section>
                            </div>
                        </div>
                        
                        
                        
<script>
  $(function() {
    var availableTags = [
      "Abarelix",
      "Ablavar",
      "Acarbose",
      "Acetaminophen",
      "Acticin",
      "Actiq",
      "Activase",
      "Acular",
      "Adapalene",
      "Adderall"
    ];
    $( "#meds" ).autocomplete({
      source: availableTags
    });
  });
  </script>