<h1>
	<?php echo $this->user->account_type_print; ?>
	<small>Control Panel</small>
</h1>
                <!-- start:breadcrumb -->
                <ol class="breadcrumb">
                    <li><a href="<?php echo $this->baseUrl("/portal"); ?>"><i class="fa fa-home"></i> Dashboard</a></li>
                    <!-- <li><a href="#"> Extras Pages</a></li>
                    <li class="active">Blank Page</li> -->
                </ol>
                <!-- end:breadcrumb -->

                <!-- start:content -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="box blank-page">
                            Welcome <?php echo $this->user->name_first; ?>!
                        </div>
                    </div>
                </div>