<h1>
	Responding...
	<small><?php echo $this->user->account_type_print; ?> Control Panel</small>
</h1>

<div class="row">
<section class="panel">
                               
                                    <div class="panel-body">
                                    	<div class="col-lg-6">
							  				<div class="alert alert-info" role="alert">
						      	<strong>Claire</strong> Letting Jim know you are on the way.
						    </div>
											</div>
                                        
                                    </div>
                                </section>                            
</div>