<h1>
	Fall Alert!
	<small><?php echo $this->user->account_type_print; ?> Control Panel</small>
</h1>

<div class="row">
<section class="panel">
                                    <header class="panel-heading">
                                        <h3>Please Respond</h3>
                                    </header>
                                    <div class="panel-body">
                                    	<div class="col-lg-6">
                                    	<div class="alert alert-danger alert-dismissible" role="alert">
							  				<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
							  					<strong>Warning!</strong> Jim Harpough's wearable has indicated a possible fall in Palestra Arena! Please Respond ASAP.
											</div>
											
                                        <img src="<?php echo $this->baseUrl("/")?>img/gmap.png" />
                                        	<a href="<?php echo $this->baseUrl("portal/responding"); ?>">
                                        	<button type="button" class="btn btn-danger btn-block btn-lg" data-original-title="" title="">On My Way</button>
                                        	</a>
                                        </div>
                                    </div>
                                </section>                            
</div>