<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head profile="http://gmpg.org/xfn/11">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	
	
	<title>IdleGuard</title>
	
	<meta name="title" content="idleguard" />
	<meta name="author" content="for community | idleguard.com" />
	<meta name="keywords" content="here, are , some, tags" />
	<meta name="description" content="some desc..." />

	<!--<link rel="stylesheet" href="<?php echo $this->baseUrl("/styles/hoverdog.css"); ?>" type="text/css" media="screen" />-->
		
	
</head>
		
<body> 
 
<div class="content"> 
	<?php echo $this->layout()->content; ?>
</div> 

</body> 
</html> 